from cosa_fva import cosa_single_swap_test
import ray
ray.init(log_to_driver=False)

cosa_single_swap_test(
    anaerobic=False,
    reac_id="TEST_0_206",
    mu=0.206,
    base_nadx_scenario="WILDTYPE",
    c_source="acetate",
)
cosa_single_swap_test(
    anaerobic=False,
    reac_id="TEST_0_156",
    mu=0.156,
    base_nadx_scenario="WILDTYPE",
    c_source="acetate",
)
cosa_single_swap_test(
    anaerobic=False,
    reac_id="TEST_0_106",
    mu=0.106,
    base_nadx_scenario="WILDTYPE",
    c_source="acetate",
)
cosa_single_swap_test(
    anaerobic=False,
    reac_id="TEST_0_056",
    mu=0.056,
    base_nadx_scenario="WILDTYPE",
    c_source="acetate",
)
cosa_single_swap_test(
    anaerobic=False,
    reac_id="TEST_0_003",
    mu=0.03,
    base_nadx_scenario="WILDTYPE",
    c_source="acetate",
)
