name: tcosa
channels:
  - conda-forge
  - defaults
  - IBMDecisionOptimization
dependencies:
  - pytest
  - pylint
  - mypy
  - autopep8
  - matplotlib-base
  - numpy<1.24
  - python=3.8
  - cobra=0.22
  - pulp
  - cplex
  - equilibrator-api=0.4
  - pip
  - pip:
    - ray
